# Generated by Django 3.2 on 2022-12-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
